### ISSUE TITLE
Release to Foxy / Galactic / Rolling

### ISSUE THREAD

**Issue by SteveMacenski** [aws-robotics/aws-robomaker-small-warehouse-world#10]
Hi,

We'd like to use this in Nav2 CI. In order to do so, we need this released as a package so that we can install it in our docker containers and have it be available for users to test within

**Comment by addhawan** [comment]
Hi, 

We'd provide you an ETA soon on this request. 

Thanks

**Comment by SteveMacenski** [comment]
What's nice too is if you release to rolling, you wont need to re-release this for future distributions, it will automatically be added as long as it continues to build

**Comment by SteveMacenski** [comment]
Any movement on this?

**Comment by cheng-kevin** [comment]
@SteveMacenski  Thanks for following up, We've prioritized this task in this coming sprint.

**Comment by cheng-kevin** [comment]
Hi Steve, we will be officially supporting ROS2 version of this sample world in the `ros2` branch, using many of the changes you have contributed.  However, after some discussion we decided we will not be releasing this sample world as a package.  

Could you use an alternate way to install this into your container? For example:
```
RUN source /opt/ros/foxy/setup.bash && cd \
  && git clone https://github.com/aws-robotics/aws-robomaker-small-warehouse-world -b ros2 \
  && rosdep install --from-paths src --ignore-src -r -y \
  && colcon build
```

**Comment by SteveMacenski** [comment]
Why not? It is very standard practice and takes quite literally less than 10 minutes. 

There is not other suitable alternative, if this is not released as a package to the build farm as all major packages are, we cannot consider this for use.

**Comment by ahtsan** [comment]
Apologize for the late reply. We prefer not to release the package as it would incur additional maintenance burdens. Is there a particular reason you are not able to clone this repository to your workspace?

**Comment by SteveMacenski** [comment]
It would take alot of words to describe to you why this is needed if you don't understand already. Rather than giving you the full technical reason, I'm just going to summarize the end impact to save a wall of text.

- Binaries are needed for all dependencies of a package for it itself to be released as binaries
- Nav2 **must** be released to binaries for users to use, so if this isn't going to be released as binaries, we cannot use it. There is no alternative.  
- We want to use it and Nav2's adoption of it would greatly speak to the character of this work, I'm sure that's worth 10 minutes of someone at AWS's time 1 time a year. This is not some unreasonable burden until you're talking about releasing 20+ packages that have active development like we do in Nav2.  Even then, I get that done in an afternoon listening to podcasts :wink: . 

Edit: I even have a really simple step-by-step bloom guide https://gist.github.com/SteveMacenski/1c321d1c9edca096ae4d763d8327c2ee. All that's needed is to run it, verify it builds, and test it that you installed the filepaths correctly (since its a gazebo package).

**Comment by ahtsan** [comment]
Thanks for the detail explanation. We decided to bloom release the package, will do it this week.

**Comment by cheng-kevin** [comment]
https://github.com/ros/rosdistro/pull/30633/files

**Comment by SteveMacenski** [comment]
You would need 3 PRs for 3 bloom runs (one for Foxy, Galactic and Rolling)

**Comment by cheng-kevin** [comment]
Thanks Steve, once this one is approved we will bloom to those distros.

**Comment by SteveMacenski** [comment]
It has been approved and merged, can we get Galactic and Rolling?

**Comment by cheng-kevin** [comment]
PRs are created for Galactic and Rolling

**Comment by SteveMacenski** [comment]
Thanks!!

**Comment by cheng-kevin** [comment]
galactic and rolling PR merged
