### ISSUE TITLE
Releases have failed: Build farm jobs dying

### ISSUE THREAD

**Issue by SteveMacenski** [aws-robotics/aws-robomaker-small-warehouse-world#15]
https://build.ros2.org/job/Rdev__aws-robomaker-small-warehouse-world__ubuntu_focal_amd64/search/?q=aws_robomaker&Jenkins-Crumb=23e6f87c3ac2781c12c317f2f660f3fd368c9d28f9584e228b55a00d6b0a6e0b

Your releases to Galactic, Foxy, and Rolling are all failing and will never be released until resolved and re-synced with bloom

**Comment by cheng-kevin** [comment]
Foxy build seems to be passing from fix bloomed last week.  I've bloomed Galactic and Rolling today.

**Comment by cheng-kevin** [comment]
Foxy, Galactic, and Rolling are all green.

**Comment by SteveMacenski** [comment]
Thanks! Great timing, we're looking to migrate over to this in the next sync!
