### ISSUE TITLE
Error Code 12 Msg: Unable to find uri[model://warehouse_pallet3]

### ISSUE THREAD

**Issue by ljaniec** [aws-robotics/aws-robomaker-small-warehouse-world#17]
Bug: 
Error message `Error Code 12 Msg: Unable to find uri[model://warehouse_pallet3]`
and lack of some models in the Gazebo (there are no small shelves).

Environment: Ubuntu 20.04, ROS 2 Foxy

Steps to reproduce:
* clone `aws-robomaker-small-warehouse-world` to workspace
* create `.rosinstall` file in the ROS2 workspace with 
```
- git: {local-name: src/aws-robomaker-small-warehouse-world, uri: 'https://github.com/aws-robotics/aws-robomaker-small-warehouse-world.git', version: ros2}
```
inside (root level)
 ```
rosws update
rosdep install --from-paths . --ignore-src -r -y
colcon build
```
* `export GAZEBO_MODEL_PATH=`pwd`/models` in the cloned package (branch: ros2)
* `gazebo worlds/no_roof_small_warehouse.world`

Running this world directly (using ROS launcher) without robot works.

**Comment by cheng-kevin** [comment]
Thanks for the ticket. We will try to reproduce this on our side first.

**Comment by ahtsan** [comment]
Where is the `models` folder in your workspace? It might be that `pwd`/models is not the correct path to the `models` folder. Do you mind sharing the directory structure of your workspace?

**Comment by ljaniec** [comment]
Hello,
I have switched to the binaries and right now I don't have this bug with invisible small shelves. I think this issue could be closed.
Models right now are in `/opt/ros/galactic/share/aws_robomaker_small_warehouse_world/models` and they are loading fine.
