### ISSUE TITLE
aws-robomaker-small-warehouse-world in ROS 2 Rolling has not been released on Ubuntu Jammy

### ISSUE THREAD

**Issue by nuclearsandwich** [aws-robotics/aws-robomaker-small-warehouse-world#21]
The ROS 2 Rolling Ridley distribution recently [migrated to Ubuntu 22.04 Jammy](https://github.com/ros/rosdistro/pull/32036) using the rosdistro migration tool.

This repository is one which failed to bloom during the migration because the `gazebo` dependency is not yet available in Ubuntu Jammy. Once the Jammy repositories and the rosdep database are updated it should be possible to release this repository in Rolling again by running bloom normally.

Packages which are not released in Rolling may not be automatically added to future stable ROS 2 distributions.

**Comment by cheng-kevin** [comment]
Thank you for the information.  We will rebloom when the dependency is available.
