### ISSUE TITLE
Why are Rolling Binaries Disabled?

### ISSUE THREAD

**Issue by SteveMacenski** [aws-robotics/aws-robomaker-small-warehouse-world#23]
The rolling binaries have been disabled to build for this package and therefore they're not available in Rolling after the migration to 22.04 since the last build was in February. Why is this disabled and can we re-enable it?

- https://build.ros2.org/job/Rbin_uF64__aws_robomaker_small_warehouse_world__ubuntu_focal_amd64__binary/
- https://build.ros2.org/job/Rbin_ufv8_uFv8__aws_robomaker_small_warehouse_world__ubuntu_focal_arm64__binary/

CC https://github.com/ros-planning/navigation2/pull/2797

**Comment by SteveMacenski** [comment]
@nuclearsandwich I can't seem to find where in https://github.com/ros2/ros_buildfarm_config this was disabled. Do you happen to have any context on this?

**Comment by nuclearsandwich** [comment]
When [Rolling migrated to Ubuntu Jammy](https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/issues/21) I opened https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/issues/21 to notify the maintainers that the package wasn't release-able on Jammy at the time. The package wasn't updated in time for the [Humble migration](https://github.com/ros/rosdistro/pull/32784) (and honestly I can't recall whether the rosdistro keys for gazebo had settled by then).

Repositories which cannot be bloomed during migration have the `version` field dropped from their release entry in distribution.yaml which effectively disables it on all platforms. https://github.com/ros/rosdistro/pull/32036/files#diff-a79d50d14101a47dfc4ea7b0dd7b9446f34b544807d8f0c48cc6a8f07fc3b36aL357

Re-blooming this repository now, assuming that all other dependencies are met, will automatically update the version field and enable release jobs for this repository.

**Comment by SteveMacenski** [comment]
Now that gazebo is released to Humble, I think this is all good now, correct? 

> Repositories which cannot be bloomed during migration have the version field dropped from their release entry in distribution.yaml 

Aaaaah, that is awfully subtle, thanks for pointing that out.

Do we really even need to rerun bloom if nothing's changed and the dependencies are met? I'd think we can just add `version: 1.0.5-1` back  --> PR opened but happy to iterate https://github.com/ros/rosdistro/pull/33458

**Comment by nuclearsandwich** [comment]
> Do we really even need to rerun bloom if nothing's changed and the dependencies are met? I'd think we can just add `version: 1.0.5-1` back --> PR opened but happy to iterate [ros/rosdistro#33458](https://github.com/ros/rosdistro/pull/33458)

Bloom needs to be re-run because the prior version of this package was generated for Ubuntu Focal not Ubuntu Jammy. While it's _possible_ that the previously generated release would work its not guaranteed and the conservative approach is to let bloom update what needs to be updated.

**Comment by nuclearsandwich** [comment]
> While it's _possible_ that the previously generated release would work its not guaranteed

Actually, it definitely won't work. The distribution name is embedded in the tags bloom generates and the ROS build farm fetches in order to create source packages. This is one of the reasons that we perform an active migration which re-runs bloom.

**Comment by SteveMacenski** [comment]
Got it - but does that work if I run bloom from my 20.04 machine, will that generate the necessary tags you mention? 

Its a problem I can't solve if bloom needs to be run again since I'm not a maintainer on this or have push access to its release repository. But we rely on it and its blocking our Humble and Rolling migration for Nav2 to 22.04

**Comment by nuclearsandwich** [comment]
> Got it - but does that work if I run bloom from my 20.04 machine, will that generate the necessary tags you mention?

Yes, it should work from any platform where the latest version of bloom (0.11.1 as of this writing) is available. Bloom generates release metadata for the platforms defined in the [`release_platforms` section of the distribution.yaml](https://github.com/ros/rosdistro/blob/8db58d767c12ffca910ccefd2068765cf11bcb63/rolling/distribution.yaml#L5-L11).
Whenever the target platforms change, bloom needs to be re-run. These platforms changed with more frequency when non-LTS versions of Ubuntu were supported but now stay relatively static for the life of a stable ROS distribution. However as Rolling is "evergreen" its platforms do change from time to time. The [migration from Ubuntu Focal to Ubuntu Jammy](https://github.com/ros/rosdistro/pull/32036) was the first such platform update for Rolling.



> Its a problem I can't solve if bloom needs to be run again since I'm not a maintainer on this or have push access to its release repository.

@cheng-kevin since you responded to #21 would you be able to do the Rolling and Humble bloom releases for this repository? Optimally we'll also migrate the release repository into the ros2-gbp organization so future automation can use it there but I can take care of that before or after the Rolling and Humble releases are made as you prefer. Thanks!

**Comment by SteveMacenski** [comment]
The fact that this is an issue for rolling feels like it should be automated away to re-run or just generate the files required for a new distribution (assuming no errors pop up) in some build farm jobs on an OS change. It kind of breaks the promise of having a `rolling` distribution if things only roll ~2 distributions before being strictly required to be re-released due to OS upgrades. I see how that's difficult though with push permissions and whatnot - all release repos for `rolling` packages would have to have a build farm agent with push rights. 

But that's here nor there for this ticket

Thanks for the info!

**Comment by nuclearsandwich** [comment]
In order to unblock dependencies of this package, I've proposed releases into rolling (https://github.com/ros/rosdistro/pull/33612) and humble (https://github.com/ros/rosdistro/pull/33613).
